"""Analyze Phase 5.7 PNG evidence generated by After Effects."""

from __future__ import annotations

from pathlib import Path
import sys

from PIL import Image


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "output"
FRAMES = OUTPUT / "RectangleSnapshotInjectionFrames"
REPORT = OUTPUT / "RectangleSnapshotInjectionReport.txt"
SAMPLE_POINT = (500, 300)

EXPECTED_VISIBILITY = {
    "CaseA": True,
    "CaseB": False,
    "CaseC": True,
    "CaseD": True,
    "CaseE": True,
}


def analyze_frame(case_name: str, expected_visible: bool) -> tuple[str, bool]:
    frame_path = FRAMES / f"{case_name}.png"

    if not frame_path.is_file():
        return f"{case_name}: missing frame {frame_path}", False

    with Image.open(frame_path) as image:
        rgba = image.convert("RGBA")

        if not (
            0 <= SAMPLE_POINT[0] < rgba.width
            and 0 <= SAMPLE_POINT[1] < rgba.height
        ):
            return (
                f"{case_name}: sample point {SAMPLE_POINT} outside "
                f"{rgba.width}x{rgba.height}",
                False,
            )

        red, green, blue, alpha = rgba.getpixel(SAMPLE_POINT)

    visible = max(red, green, blue) >= 128 and alpha >= 128
    passed = visible == expected_visible
    expectation = "visible" if expected_visible else "transparent"

    return (
        f"{case_name}: rgba=({red}, {green}, {blue}, {alpha}), "
        f"expected={expectation}, observed="
        f"{'visible' if visible else 'transparent'}, "
        f"{'PASS' if passed else 'FAIL'}",
        passed,
    )


def main() -> int:
    if not REPORT.is_file():
        print(f"Missing report: {REPORT}", file=sys.stderr)
        return 1

    report_text = REPORT.read_text(encoding="utf-8-sig")
    script_passed = "SCRIPT RESULT: PASS" in report_text
    lines = [
        "",
        "External PNG pixel analysis",
        f"Pillow version: {Image.__version__}",
        f"Sample point: [{SAMPLE_POINT[0]}, {SAMPLE_POINT[1]}]",
    ]
    all_frames_passed = True

    for case_name, expected_visible in EXPECTED_VISIBILITY.items():
        line, passed = analyze_frame(case_name, expected_visible)
        lines.append(line)
        all_frames_passed = all_frames_passed and passed

    overall_passed = script_passed and all_frames_passed
    lines.append(
        "END-TO-END RESULT: " + ("PASS" if overall_passed else "FAIL")
    )

    with REPORT.open("a", encoding="utf-8") as report_file:
        report_file.write("\n".join(lines))
        report_file.write("\n")

    print("\n".join(lines))
    return 0 if overall_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
